### ISSUE TITLE
Aufteilung PHP und Perl

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2#6]
Hi @mschlenstedt 

kannst du das Repo umbenennen in LoxBerry-Plugin-SamplePlugin-V2-Perl und die PHP-Spezifika hinauswerfen.
Ich habe ein PHP-Repo erzeugt, weil es mehr Sinn macht, zwei eigene Samples zu machen.
Das sprachunabhängige Zeug (daemons, usw.) kann man dann immer noch zusammenkopieren.

lg, Christian

**Comment by mschlenstedt** [comment]
Erledigt
