### ISSUE TITLE
sudoers example uses absolut path

### ISSUE THREAD

**Issue by andweber** [mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2#7]
Sample file for sudoers:
`# Sudoers file for the plugin. Note: All scripts in sbin will be added automatically
%loxberry ALL = NOPASSWD: /opt/loxberry/sbin/hereiswhatwehavetodoasroot`

either $LBHOMEDIR can be used or the install check for absolute path should exclude this?

**Comment by christianTF** [comment]
`$LBHOMEDIR` does not work inside a sudoers file.

Basically, the sample plugin should not show the system sbin directory as example.

The replacement variable should be used, e.g. 
`REPLACELBPBINDIR/myscript.sh`
is replaced during installation by 
`/opt/loxberry/bin/plugins/pluginname/myscript.sh`

http://www.loxwiki.eu/pages/viewpage.action?pageId=23462653

**Comment by mschlenstedt** [comment]
Bau ich in die Anleitung zum erstellen der Plugins V2 ein. 

Was ist mit dem Crontab File? Das sollten wir auch überprüfen.

**Comment by andweber** [comment]
doen with commit #9
